### ISSUE TITLE
Persist data volume

### ISSUE THREAD

**Issue by cojack** [axibase/dockers#72]
Hi,
I have a problem that Im going to mount external volume to persist axibase data there, but I can not do it using /opt/atsd because it have whole atsd installation, how can I achieve that?

**Comment by rodionos** [comment]
Greetings, please take a look at this [note](https://axibase.com/docs/atsd/administration/change-data-directory.html) on how to customize the data directory.

**Comment by cojack** [comment]
@rodionos it still doesn't help me without mapped additional VOLUME as exposed one. Do you accept PR?

**Comment by rodionos** [comment]
@cojack - We'll definitely take a look at the PR. Thanks.

**Comment by rodionos** [comment]
@cojack 

The container configuration is such that the HDFS fails to start.

Could you please check that it can be done manually, for example, by exposing a custom data directory to the container on a mount point other than  `/opt/atsd`. Then proceed to modify the default data directory according to instruction linked earlier to verify that the manual process works.

**Comment by rodionos** [comment]
HDFS fails to start because directories `/opt/atsd/hdfs-data`, `/opt/atsd/hdfs-cache` and `/opt/atsd/hdfs-data-name` are empty:

```
axibase@cojack_axibase:/$ find /opt/atsd/ -type d -empty | sort -r
/opt/atsd/hdfs-data-name
/opt/atsd/hdfs-data
/opt/atsd/hdfs-cache
```

There are 2 types of volumes:

1. [Bind mounts](https://docs.docker.com/storage/bind-mounts/)
1. [Named volumes](https://docs.docker.com/storage/volumes/)

The following are `bind` mounts:

```yml
    volumes:
      - ./atsd/hdfs-data:/opt/atsd/hdfs-data
      - ./atsd/hdfs-cache:/opt/atsd/hdfs-cache
      - ./atsd/hdfs-data-name:/opt/atsd/hdfs-data-name
```

From [docs](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems):


> The **nocopy** modes is used to disable automatic copying requested volume
path in the container to the volume storage location. For named volumes, `copy` is the default mode. **Copy modes are not supported for bind-mounted volumes.**

That means that **nocopy** is set by default for the bind mounts and can't be changed.

The same described in [Mounting into a non-empty directory on the container](https://docs.docker.com/storage/bind-mounts/#mounting-into-a-non-empty-directory-on-the-container).

The workarounds are [here](https://github.com/docker/docker.github.io/issues/2979#issuecomment-296289081).

**Comment by cojack** [comment]
@rodionos this is not even a partially solution, I have spend over week to figure out some workaround and there is NONE. Copy data over and over is not a solution at all, I can not have named volumes because they can not be stored in different path than `data-root` is but somehow docker doesn't allow me to change `data-root` to my mounted net volume and Im in DS. I can not persist data of axibase right now and I don't have any clue where looking for solution right now.

I need any advice.

**Comment by rodionos** [comment]
@cojack 

Here's a manual workaround using the current image. We'll be making changes to the image so that the data directory formatting is done behind the scenes just by passing an environment variable.

---

* Launch container with mapped data volumes. **Make sure the directories are empty.**

```sh
docker run -p 8443:8443 \
  -v /tmp/atsd/hdfs-cache:/opt/atsd/hdfs-cache \
  -v /tmp/atsd/hdfs-data:/opt/atsd/hdfs-data \
  -v /tmp/atsd/hdfs-data-name:/opt/atsd/hdfs-data-name \
  --name atsd axibase/atsd
```

* ATSD (or rather HDFS) will fail to start as before.

* Log in to the container shell.

```
docker exec -it atsd bash
```

* Stop atsd

```
/opt/atsd/bin/atsd-all.sh stop
```

* Format data directory

```
/opt/atsd/hadoop/bin/hadoop namenode -format
```

* Start ATSD

```
/opt/atsd/bin/atsd-all.sh start
```

**Comment by cojack** [comment]
@rodionos there is another problem, those volumes are mounted as `root:root` then HDFS doesn't have permission to create directories there.

**Comment by cojack** [comment]
Hmm at last after I chmod these directories up to 777, then format pass but restarting HDFS 

```console
ubuntu@ip-10-0-1-197:~/axibase/dockers$ docker exec -it atsd /opt/atsd/bin/atsd-all.sh start
[ATSD] ========================================
[ATSD] Start initiated at 2018-09-05 09-31-00
[ATSD] ========================================
[ATSD] Starting HDFS. Host: 443226eaa825. Time: 2018-09-05 09-31-00.
[ATSD] Checking HDFS safemode ...
[ATSD] Safemode is off.
[ATSD] Checking HDFS for corrupt files ...
[ATSD] No corrupt files found in HDFS.
[ATSD] Checking HDFS availability ...
[ATSD] HDFS is available.
[ATSD] DataNode is not running.
[ATSD] Failed to start HDFS. Time: 2018-09-05 09-31-24.
[ATSD] Review 'Troubleshooting' and 'Restarting' sections in https://github.com/axibase/atsd/blob/master/administration/restarting.md
```

```logs
[ATSD] ========================================
[ATSD] Start initiated at 2018-09-05 09-33-11
[ATSD] ========================================
[ATSD] Starting HDFS. Host: 443226eaa825. Time: 2018-09-05 09-33-11.
[ATSD] HDFS openjdk version "1.8.0_181"
Starting namenodes on [localhost]
[ATSD] HDFS openjdk version "1.8.0_181"
localhost: starting namenode, logging to /opt/atsd/hadoop/logs/hadoop-axibase-namenode-443226eaa825.out
[ATSD] HDFS openjdk version "1.8.0_181"
localhost: starting datanode, logging to /opt/atsd/hadoop/logs/hadoop-axibase-datanode-443226eaa825.out
[ATSD] HDFS openjdk version "1.8.0_181"
Starting secondary namenodes [0.0.0.0]
[ATSD] HDFS openjdk version "1.8.0_181"
0.0.0.0: starting secondarynamenode, logging to /opt/atsd/hadoop/logs/hadoop-axibase-secondarynamenode-443226eaa825.out
[ATSD] HDFS openjdk version "1.8.0_181"
[ATSD] HDFS openjdk version "1.8.0_181"
[ATSD] HDFS tests skipped.
[ATSD] Checking HDFS availability ...
[ATSD] HDFS openjdk version "1.8.0_181"
[ATSD] HDFS is available.
[ATSD] DataNode is not running.
[ATSD] Failed to start HDFS. Time: 2018-09-05 09-33-29.
[ATSD] Review 'Troubleshooting' and 'Restarting' sections in https://github.com/axibase/atsd/blob/master/administration/restarting.md
[ATSD] Failed to start ATSD. Check /opt/atsd/atsd/logs/start.log file.
```

And I have tried this solution https://github.com/axibase/atsd/blob/master/administration/restarting.md#file-permissions without luck 

```console
ubuntu@ip-10-0-1-197:~/axibase/dockers$ docker exec -it atsd bash
axibase@443226eaa825:/$ ls -la /tmp/hsperfdata_axibase/
total 72
drwxr-xr-x 1 axibase axibase  4096 Sep  5 09:33 .
drwxrwxrwt 1 root    root     4096 Sep  5 09:27 ..
-rw------- 1 axibase axibase 32768 Sep  5 09:40 311
-rw------- 1 axibase axibase 32768 Sep  5 09:40 733
axibase@443226eaa825:/$ rm -rf /tmp/hsperfdata_axibase
axibase@443226eaa825:/$ exit
exit
ubuntu@ip-10-0-1-197:~/axibase/dockers$ docker exec -it atsd /opt/atsd/bin/atsd-all.sh start
[ATSD] ========================================
[ATSD] Start initiated at 2018-09-05 09-40-47
[ATSD] ========================================
[ATSD] Starting HDFS. Host: 443226eaa825. Time: 2018-09-05 09-40-47.
[ATSD] Checking HDFS safemode ...
[ATSD] Safemode is off.
[ATSD] Checking HDFS for corrupt files ...
[ATSD] No corrupt files found in HDFS.
[ATSD] Checking HDFS availability ...
[ATSD] HDFS is available.
[ATSD] DataNode is not running.
[ATSD] Failed to start HDFS. Time: 2018-09-05 09-41-10.
[ATSD] Review 'Troubleshooting' and 'Restarting' sections in https://github.com/axibase/atsd/blob/master/administration/restarting.md
```

Any other advice?

**Comment by rodionos** [comment]
> Did you try your solution, it works for you? If then, how?

@cojack 

Yes, my example worked for me. I created new sub-directories in the `/tmp` folder as a regular user on MacOS and was able to start ATSD as described.

You could try the following: make sure that the UID of the owner of the subdirectories is the same in the container and on the host.

Check the id of the user in the container:

```
id -u axibase
id -g axibase
```

Grant ownership of the subdirectories to the same UID, for example to `1000` if the above command in the container returns `1000`:

```
sudo chown -R 1000:1000 /tmp/atsd
```

**Comment by rodionos** [comment]
@cojack ,

To resolve permission issues, execute steps as described below. Let us know if this works for you.

Start container:

```bash
docker run \
  --detach \
  --name=atsd \
  -p 8088:8088 \
  -p 8443:8443 \
  -p 8081:8081 \
  -p 8082:8082/udp \
  -v /tmp/atsd/hdfs-cache:/opt/atsd/hdfs-cache \
  -v /tmp/atsd/hdfs-data:/opt/atsd/hdfs-data \
  -v /tmp/atsd/hdfs-data-name:/opt/atsd/hdfs-data-name \
  axibase/atsd:latest
```

ATSD will **fail** to start which is expected.

```bash
docker logs -f atsd
```

```bash
[ATSD] ========================================
[ATSD] Start initiated at 2018-09-06 15-30-57
[ATSD] ========================================
[ATSD] Starting HDFS. Host: 2c206c3a3f0c. Time: 2018-09-06 15-30-57.
[ATSD] HDFS tests skipped.
[ATSD] Checking HDFS availability ...
ls: Call From 2c206c3a3f0c/172.17.0.2 to localhost:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[ATSD] HDFS is not available.
[ATSD] Review 'Troubleshooting' and 'Restarting' sections in https://github.com/axibase/atsd/blob/master/administration/restarting.md
[ATSD] Failed to start HDFS. Time: 2018-09-06 15-31-13.
[ATSD] Failed to start ATSD. Check /opt/atsd/atsd/logs/start.log file.
```

Stop all ATSD processes:

```bash
docker exec atsd /opt/atsd/bin/atsd-all.sh stop
```

Change ownership:

```bash
docker exec -u root atsd chown -R axibase:axibase /opt/atsd
```

Format HDFS:

```bash
docker exec atsd /opt/atsd/hadoop/bin/hdfs namenode -format
```

Start ATSD:

```bash
docker exec atsd /opt/atsd/bin/atsd-all.sh start
```

**Comment by rodionos** [comment]
@cojack 

Does the latest instruction set work for you as outline? Any changes are necessary for your use case?

**Comment by cojack** [comment]
@rodionos sorry for inactivity, yes, your final solution is working like a charm.

> Any changes are necessary for your use case?

Yes, in Dockerfile there are 3 paths that need to be exposed:

```diff
diff --git a/Dockerfile b/Dockerfile
index 1a8610e..40687fb 100755
--- a/Dockerfile
+++ b/Dockerfile
@@ -29,6 +29,6 @@ USER axibase
 # jmx, network commands(tcp), network commands(udp), graphite, http, https
 EXPOSE 1099 8081 8082/udp 8084 8088 8443
 
-VOLUME ["/opt/atsd"]
+VOLUME ["/opt/atsd/hdfs-cache", "/opt/atsd/hdfs-data", "/opt/atsd/hdfs-data-name"]
 
 ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
```

and thats it. 

Thank you very much.

**Comment by rodionos** [comment]
@cojack 

> -VOLUME ["/opt/atsd"]

Wouldn't this imply that data in `/opt/atsd/atsd/conf`, for example, is now persisted differently? This directory contains ssl certificate files, configuration files, rule engine scripts etc. They are installation specific, just like the data directories.

The current declaration ensures that the entire `/opt/atsd` is an externally mounted volume.

**Comment by cojack** [comment]
@rodionos you're right, it seems that path is enough, thank you again.

**Comment by rodionos** [comment]
Documented on https://github.com/axibase/atsd/blob/master/installation/docker.md#custom-data-directories. Closing
